- name: Enable Tor service
  ansible.builtin.service:
    name: tor
    enabled: yes
  tags:
    - enable
    - install_all

- name: Start Tor service
  ansible.builtin.service:
    name: tor
    state: started
