- name: Install M:Tier openup
  ansible.builtin.get_url:
    url: https://stable.mtier.org/openup
    dest: /usr/local/bin/openup
    mode: 0755
  tags:
    - install_all

- name: Run openup
  ansible.builtin.shell: "/usr/local/bin/openup -N"
